### ISSUE TITLE
With the migration to Xenial, Trusty and Xenial deployments (ubuntu) are broken. gpg key issue

### ISSUE THREAD

**Issue by varunmehta** [GluuFederation/docs#100]
When installing gluu-server on (Ubuntu 16.04) Xenial, it fails with an error message; 

`W: https://repo.gluu.org/ubuntu/dists/xenial/Release.gpg: Signature by key 5E2751618B45466B417A099A5B76117E0544BA38 uses weak digest algorithm (SHA1)`

As per [this post](http://askubuntu.com/questions/764927/key-uses-weak-digest-algorithm), 16.04 has started ignoring SHA1 keys. 

When reverted back to Trusty (Ubuntu 14.04), the installation fails with 

`W: Conflicting distribution: https://repo.gluu.org trusty Release (expected trusty but got xenial)`

Please update the Release.gpg key, so it can be used with Xenial.

**Comment by adrian-gluu** [comment]
you should use xenial yet we didn't finish the xenial pkg yet, also our trusty deb pkg only works in trusty because xenial comes with a new init "systemD", please if you want to use gluu-server try it just in trusty machine using our trusty deb pkg. our trusty deb pkg is not compatible with xenial sorry!

**Comment by varunmehta** [comment]
I tried on 14.04 & 16.04. Installation failed on both the systems.

**Comment by zamilskhan** [comment]
Please open a ticket in the [support portal](support.gluu.org)
