### ISSUE TITLE
Missing reference docs for oxauth config JSON data structure

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/docs#23]
OxAuth configuration needs more detail.

We list the file here, but its not in an easy to consume format.
http://www.gluu.org/docs/reference/oxAuth

Also, there is a configuration JSON file. Does it correspond exactly to the XML? What are the fields and guidelines for values?

**Comment by aliaksander-samuseu** [comment]
This is a very old ticket. No files like that (aside from LDAP configuration files) exist anymore in tomcat/conf directory. I also can't find any section that does these mappings between attributes/claims/scopes, may be because it's not needed anymore, they are stored in different attributes in LDAP at the moment.

**Comment by aliaksander-samuseu** [comment]
I'm updating this doc articles atm.

**Comment by zamilskhan** [comment]
#27 also has the same issue. we should use one to track.
